# Generated by Django 2.0.2 on 2018-02-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sales_agent',
            field=models.BooleanField(default=False),
        ),
    ]
