# Generated by Django 2.0.3 on 2018-03-24 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180324_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregationcenterproduct',
            name='active',
        ),
        migrations.AlterField(
            model_name='aggregationcenterproduct',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
