# Generated by Django 2.0.3 on 2018-04-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='price in Ksh.', max_digits=9),
        ),
    ]
