# Generated by Django 2.0.3 on 2018-04-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180407_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='common_price',
        ),
    ]
