# Generated by Django 2.0.3 on 2018-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180416_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationcenterproduct',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in kgs.', max_digits=8),
        ),
    ]
