# Generated by Django 2.0.3 on 2018-04-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aggregationcenterproduct_remaining'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aggregationcenterproduct',
            unique_together={('aggregation_center', 'product')},
        ),
    ]
