# Generated by Django 2.0.3 on 2018-04-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180421_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aggregationcenterproduct',
            unique_together=set(),
        ),
    ]
