# Generated by Django 2.0.2 on 2018-02-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180205_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_sales_agent',
        ),
    ]
