# Generated by Django 2.0.3 on 2018-04-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180426_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcenterproduct',
            options={'verbose_name': 'Product Availability', 'verbose_name_plural': 'Product Availability'},
        ),
    ]
