# Generated by Django 2.0.2 on 2018-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_is_sales_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcenter',
            options={'verbose_name': 'Aggregation Center', 'verbose_name_plural': 'Aggregation Center'},
        ),
        migrations.AlterField(
            model_name='aggregationcenterproduct',
            name='active',
            field=models.BooleanField(default=True, help_text='If the product is sale in this aggregation center'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cratetype',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kgs)'),
        ),
    ]
