# Generated by Django 2.0.3 on 2019-02-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180430_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcenter',
            options={'permissions': (('can_delete_center', 'delete aggregation center'),), 'verbose_name': 'Aggregation Center', 'verbose_name_plural': 'Aggregation Centers'},
        ),
    ]
