# Generated by Django 2.0.3 on 2019-02-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190206_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcenter',
            options={'verbose_name': 'Aggregation Center', 'verbose_name_plural': 'Aggregation Centers'},
        ),
    ]
