# Generated by Django 2.0.2 on 2018-02-08 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aggregationcenter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='crate',
            name='procurement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aggregationcenterproduct',
            name='active',
            field=models.BooleanField(default=True, help_text='If the product is sale in this aggregation center', verbose_name='Available'),
        ),
    ]
