# Generated by Django 2.0.3 on 2019-02-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190206_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcenterproduct',
            options={'permissions': (('view_productavailabilitylist', 'view product availability'),), 'verbose_name': 'Product Availability', 'verbose_name_plural': 'Product Availability'},
        ),
    ]
