# Generated by Django 2.0.2 on 2018-02-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20180226_0946'),
        ('core', '0013_auto_20180208_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
