# Generated by Django 2.0.3 on 2018-03-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcenter',
            options={'verbose_name': 'Aggregation Center', 'verbose_name_plural': 'Aggregation Centers'},
        ),
    ]
