# Generated by Django 2.0.3 on 2018-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, unique=True)),
                ('runs', models.CharField(choices=[('O', 'Once'), ('M', 'Multiple')], max_length=1)),
                ('run_times', models.PositiveSmallIntegerField()),
                ('last_run', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
