# Generated by Django 2.0.3 on 2018-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='run_times',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
