# Generated by Django 2.0.3 on 2018-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bank where cash from sales is deposited.List M-pesa paybill here too.The bank name can not be removed from this list once there has been cash deposit records added', max_length=200)),
            ],
        ),
    ]
