# Generated by Django 2.0.3 on 2018-06-19 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cash_breakdown', '0002_cashdeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('narration', models.TextField()),
            ],
        ),
    ]
