# Generated by Django 2.0.3 on 2018-08-31 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cash_breakdown', '0004_auto_20180620_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
