# Generated by Django 2.0.3 on 2018-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_breakdown', '0005_auto_20180831_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashexpense',
            name='narration',
            field=models.TextField(blank=True, help_text='e.g, KAR Fuel'),
        ),
    ]
