# Generated by Django 2.0.3 on 2018-03-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Returns',
            new_name='Return',
        ),
    ]
