# Generated by Django 2.0.3 on 2018-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default='2000-01-01', verbose_name='date of delivery'),
            preserve_default=False,
        ),
    ]
