# Generated by Django 2.0.3 on 2018-03-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180312_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageproduct',
            name='qty_order',
        ),
    ]
