# Generated by Django 2.0.3 on 2018-04-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0002_auto_20180403_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_delivery',)},
        ),
        migrations.RemoveField(
            model_name='bbf',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bbf',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bbf',
            name='number',
        ),
        migrations.AddField(
            model_name='bbf',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
