# Generated by Django 2.0.3 on 2018-03-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.CustomerDiscount'),
        ),
    ]
