# Generated by Django 2.0.3 on 2018-03-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_orderproduct_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OverPay',
            new_name='BBF',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.CustomerDiscount'),
        ),
    ]
