# Generated by Django 2.0.3 on 2018-04-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20180405_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_delivery', '-created_at')},
        ),
        migrations.AddField(
            model_name='cashreceiptparticular',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cashreceiptparticular',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% discount', max_digits=5),
        ),
    ]
