# Generated by Django 2.0.3 on 2018-03-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0005_auto_20180323_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderlessParticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, help_text='This is the unitprice for each quantity', max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, help_text='% discount', max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Receipt')),
            ],
        ),
    ]
