# Generated by Django 2.0.2 on 2018-02-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_active'),
        ('sales', '0005_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_order', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qty_weigh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('crate_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
    ]
