# Generated by Django 2.0.3 on 2018-03-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0006_orderlessparticular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptparticular',
            name='package_product',
        ),
        migrations.AddField(
            model_name='receiptparticular',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
            preserve_default=False,
        ),
    ]
