# Generated by Django 2.0.3 on 2018-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20180407_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprice',
            name='negotiated_price',
            field=models.BooleanField(default=False),
        ),
    ]
