# Generated by Django 2.0.3 on 2018-04-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_customerprice_negotiated_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditsettlement',
            old_name='served_by',
            new_name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='creditsettlement',
            name='receipt',
        ),
        migrations.AddField(
            model_name='creditsettlement',
            name='check_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditsettlement',
            name='customer',
            field=models.ForeignKey(default='GRFNHH', help_text='search by customer', on_delete=django.db.models.deletion.CASCADE, to='sales.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsettlement',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='creditsettlement',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='creditsettlement',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditsettlement',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cheque'), (2, 'Mpesa'), (3, 'Cash'), (4, 'Bank Transfer')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsettlement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerprice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='This is the unit price for each quantity', max_digits=9),
        ),
    ]
