# Generated by Django 2.0.3 on 2018-03-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180324_1245'),
        ('sales', '0007_auto_20180323_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDistributionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AggregationCenter')),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.OrderProduct')),
            ],
        ),
    ]
