# Generated by Django 2.0.2 on 2018-02-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_active'),
        ('sales', '0008_customerdiscounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDiscounts',
            new_name='CustomerDiscount',
        ),
    ]
