# Generated by Django 2.0.3 on 2018-04-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20180408_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbf',
            name='bbf_type',
            field=models.CharField(choices=[('p', 'Payment'), ('r', 'Returns Credit Note'), ('c', 'Credit Settlement Excess'), ('s', 'Pre System')], default='p', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bbf',
            name='receipt',
            field=models.ForeignKey(help_text='search by receipt no.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Receipt'),
        ),
    ]
