# Generated by Django 2.0.2 on 2018-02-03 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0009_auto_20180203_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('date_returned', models.DateField(null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Crate')),
                ('held_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Customer')),
            ],
        ),
    ]
