# Generated by Django 2.0.2 on 2018-02-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crate'),
        ('sales', '0010_salescrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProductCrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Crate')),
            ],
        ),
        migrations.RenameModel(
            old_name='PackageProducts',
            new_name='PackageProduct',
        ),
        migrations.AddField(
            model_name='packageproductcrate',
            name='package_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.PackageProduct'),
        ),
    ]
