# Generated by Django 2.0.3 on 2018-04-10 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20180410_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
