# Generated by Django 2.0.3 on 2018-04-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20180410_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceiptparticular',
            name='discount',
        ),
    ]
