# Generated by Django 2.0.3 on 2018-04-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_cashreceiptparticular_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
