# Generated by Django 2.0.2 on 2018-02-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_crate'),
        ('sales', '0013_receiptparticular'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('served_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashReceiptParticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, help_text='This is the unitprice for each quantity', max_digits=9)),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('discount', models.DecimalField(decimal_places=2, help_text='% discount', max_digits=5)),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CashReceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CashReceiptPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Cheque'), (2, 'Mpesa'), (3, 'Cash'), (4, 'Credit'), (5, 'Bank Transfer')])),
                ('check_number', models.CharField(max_length=50, null=True)),
                ('transaction_id', models.CharField(max_length=15, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True)),
                ('date_to_pay', models.DateField(null=True)),
                ('transfer_code', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CashReceipt')),
            ],
        ),
    ]
