# Generated by Django 2.0.3 on 2018-04-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20180411_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbfBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Customer')),
            ],
        ),
    ]
