# Generated by Django 2.0.2 on 2018-02-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_cashreceipt_cashreceiptparticular_cashreceiptpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceiptparticular',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='customerprice',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='packageproduct',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grade'),
        ),
        migrations.AlterField(
            model_name='receiptparticular',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grade'),
        ),
    ]
