# Generated by Django 2.0.3 on 2018-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_bbfbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbfbalance',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
