# Generated by Django 2.0.3 on 2018-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_bbfbalance_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbf',
            name='bbf_type',
            field=models.CharField(choices=[('p', 'Balance Carried Forward'), ('r', 'Returns Credit Note'), ('c', 'Credit Settlement Excess'), ('s', 'Pre System')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bbfbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
