# Generated by Django 2.0.2 on 2018-02-05 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180205_1132'),
        ('sales', '0016_creditsettlement_overpayorunderpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnsOrRejects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Return'), (2, 'Reject')])),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('date_of_resuplly', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customer')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Receipt')),
            ],
        ),
    ]
