# Generated by Django 2.0.3 on 2018-04-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20180413_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbfbalance',
            options={'ordering': ('balance',)},
        ),
    ]
