# Generated by Django 2.0.2 on 2018-02-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_returnsorrejects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptparticular',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='% discount', max_digits=5, null=True),
        ),
    ]
