# Generated by Django 2.0.3 on 2018-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20180413_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlessparticular',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderlessparticular',
            name='receipt',
        ),
        migrations.AddField(
            model_name='receiptparticular',
            name='type',
            field=models.CharField(choices=[('O', 'Ordered'), ('L', 'Orderless')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderlessParticular',
        ),
    ]
