# Generated by Django 2.0.2 on 2018-02-06 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20180206_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsorrejects',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
