# Generated by Django 2.0.2 on 2018-02-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20180206_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsorrejects',
            name='date_of_resuplly',
            field=models.DateField(null=True),
        ),
    ]
