# Generated by Django 2.0.3 on 2018-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20180413_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='bbf_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
