# Generated by Django 2.0.3 on 2018-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_receipt_bbf_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receiptparticular',
            name='type',
            field=models.CharField(choices=[('O', 'Ordered'), ('L', 'Orderless')], default='O', max_length=1),
        ),
    ]
