# Generated by Django 2.0.3 on 2018-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20180416_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
