# Generated by Django 2.0.3 on 2018-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('R', 'Reject'), ('U', 'Unripe'), ('C', 'Can Ripen'), ('S', 'Un Edible')], max_length=1),
        ),
    ]
