# Generated by Django 2.0.2 on 2018-03-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20180305_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Shop Name',
            new_name='shop_name',
        ),
    ]
