# Generated by Django 2.0.3 on 2018-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20180416_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('R', 'Reject'), ('U', 'Unripe'), ('C', "Can't Ripen"), ('S', 'Un Edible')], max_length=1),
        ),
    ]
