# Generated by Django 2.0.3 on 2018-04-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20180416_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
