# Generated by Django 2.0.3 on 2018-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20180305_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptparticular',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
