# Generated by Django 2.0.3 on 2018-03-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_receiptparticular_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'proxy': True,
                'indexes': [],
            },
            bases=('sales.receipt',),
        ),
    ]
