# Generated by Django 2.0.3 on 2018-04-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_return_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='receipt',
        ),
    ]
