# Generated by Django 2.0.3 on 2018-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceiptpayment',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashreceiptpayment',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashreceiptpayment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashreceiptpayment',
            name='transfer_code',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
