# Generated by Django 2.0.3 on 2018-04-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180421_1315'),
        ('sales', '0027_remove_return_receipt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdistributionpoint',
            unique_together={('center', 'order_product')},
        ),
    ]
