# Generated by Django 2.0.3 on 2018-04-21 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20180421_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbf',
            name='returns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Return'),
        ),
        migrations.AlterField(
            model_name='return',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
