# Generated by Django 2.0.3 on 2018-03-09 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20180309_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customer')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Receipt')),
            ],
        ),
        migrations.RemoveField(
            model_name='overpayorunderpay',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='overpayorunderpay',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='OverPayOrUnderPay',
        ),
    ]
