# Generated by Django 2.0.3 on 2018-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_auto_20180310_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
