# Generated by Django 2.0.3 on 2018-03-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20180310_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
