# Generated by Django 2.0.3 on 2018-04-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20180425_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nofication_by',
            field=models.CharField(blank=True, choices=[('e', 'Email'), ('p', 'Phone')], max_length=1),
        ),
    ]
