# Generated by Django 2.0.3 on 2018-04-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_customer_nofication_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='nofication_by',
            new_name='notification_by',
        ),
    ]
