# Generated by Django 2.0.3 on 2018-03-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_auto_20180310_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceipt',
            name='number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='number',
        ),
    ]
