# Generated by Django 2.0.3 on 2018-04-25 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180423_1633'),
        ('sales', '0032_auto_20180425_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderlessPackage',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='notification_by',
            field=models.CharField(blank=True, choices=[('e', 'Email'), ('p', 'Phone')], help_text='This is how notification will be sent to the customer,in case of debt settlement alerts or customer statement sending', max_length=1),
        ),
        migrations.AlterField(
            model_name='receiptparticular',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% discount', max_digits=5, null=True),
        ),
    ]
