# Generated by Django 2.0.3 on 2018-04-25 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_auto_20180425_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDeposit',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('via', models.CharField(choices=[('M', 'M-pesa'), ('B', 'Bank Transfer'), ('C', 'Cash'), ('Q', 'Cheque')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=10)),
                ('cheque_number', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Customer')),
            ],
        ),
    ]
