# Generated by Django 2.0.3 on 2018-04-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_customerdeposit_received_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptMisc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='The balance before a receipt payment was made', max_digits=12)),
                ('receipt', models.OneToOneField(help_text='Receipt can have only one balance', on_delete=django.db.models.deletion.CASCADE, to='sales.Receipt')),
            ],
        ),
        migrations.AddField(
            model_name='customeraccountbalance',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
