# Generated by Django 2.0.3 on 2018-04-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_auto_20180426_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='type',
            field=models.CharField(choices=[('R', 'Return'), ('P', 'Purchase'), ('D', 'Deposit'), ('A', 'Payment')], max_length=1),
        ),
    ]
