# Generated by Django 2.0.3 on 2018-04-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_auto_20180426_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraccountbalance',
            old_name='balance',
            new_name='amount',
        ),
    ]
