# Generated by Django 2.0.3 on 2018-04-26 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_auto_20180426_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbf',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='type',
            field=models.CharField(choices=[('R', 'Return'), ('P', 'Purchase'), ('D', 'Deposit'), ('A', 'Payment'), ('B', 'BBF')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='via',
            field=models.CharField(blank=True, choices=[('M', 'M-pesa'), ('B', 'Bank Transfer'), ('C', 'Cash'), ('Q', 'Cheque')], max_length=1),
        ),
    ]
