# Generated by Django 2.0.3 on 2018-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_return_replaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('R', 'Rotten'), ('U', 'Unripe'), ('O', 'Overripe'), ('P', 'Poor Quality'), ('E', 'Excess')], max_length=1),
        ),
    ]
