# Generated by Django 2.0.3 on 2018-05-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_auto_20180503_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashreceipt',
            options={'ordering': ('-date',)},
        ),
    ]
