# Generated by Django 2.0.3 on 2018-05-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_auto_20180527_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketreturn',
            name='type',
            field=models.CharField(choices=[('U', 'UnSalvageable'), ('S', 'Salvageable')], default='S', max_length=1),
        ),
    ]
