# Generated by Django 2.0.3 on 2018-05-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_marketreturn_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTotalDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, help_text='% discount', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customertotaldiscount',
            unique_together={('customer', 'discount')},
        ),
    ]
