# Generated by Django 2.0.3 on 2018-06-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_auto_20180531_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilledTogether',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('box', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BilledTogetherCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.BilledTogether')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Customer')),
            ],
        ),
    ]
