# Generated by Django 2.0.3 on 2018-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_auto_20180602_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billedtogether',
            name='box',
            field=models.CharField(blank=True, max_length=100, verbose_name='P.O Box'),
        ),
        migrations.AlterField(
            model_name='billedtogether',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Billing Name'),
        ),
    ]
