# Generated by Django 2.0.3 on 2018-06-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0055_customerdeposit_remaining_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdeposit',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('-date',), 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
