# Generated by Django 2.0.3 on 2018-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_auto_20180604_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='settling_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
