# Generated by Django 2.0.3 on 2018-06-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_auto_20180604_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='settling_amount',
            new_name='balance',
        ),
    ]
