# Generated by Django 2.0.3 on 2018-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_auto_20180605_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(help_text='The customer can not be deleted once a sale has been recorded or a bbf.', max_length=100, unique=True),
        ),
    ]
