# Generated by Django 2.0.3 on 2018-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_auto_20180911_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
