# Generated by Django 2.0.3 on 2018-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_auto_20180911_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
