# Generated by Django 2.0.3 on 2019-02-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_auto_20180911_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ('-date',), 'permissions': (('view_returnedlist', 'can view returned list'),)},
        ),
    ]
