# Generated by Django 2.0.3 on 2019-02-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_auto_20190207_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbf',
            options={'permissions': (('view_bbf', 'can view bbf'),)},
        ),
        migrations.AlterModelOptions(
            name='cashreceipt',
            options={'ordering': ('-date',), 'permissions': (('view_cashreceipts', 'can view cash receipts'),)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('view_customerstatement', 'can view customer statement'), ('view_customers', 'can view customers '))},
        ),
        migrations.AlterModelOptions(
            name='marketreturn',
            options={'permissions': (('view_marketreturn', 'can view market return '),)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_delivery', '-created_at'), 'permissions': (('view_order', 'can view order'),)},
        ),
        migrations.AlterModelOptions(
            name='orderlesspackage',
            options={'permissions': (('view_orderlesspackage', 'can view orderless package'),)},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'permissions': (('view_orderproducts', 'can view order products'),), 'verbose_name': 'Order Report', 'verbose_name_plural': 'Order Reports'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'permissions': (('view_regions', 'can view regions'),)},
        ),
    ]
